name: Build Docker Image and Push to Docker Hub

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -e -B package --file pom.xml

    - name: Build Docker image
      run: docker build -t vulpeszerda27/bookshop-backend:$GITHUB_SHA .

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image
      run: docker push vulpeszerda27/bookshop-backend:$GITHUB_SHA

      # Set up SSH for deployment
    - name: Setup SSH
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key

      # Execute script on remote server
    - name: Deploy to remote server
      run: ssh -i private_key -o StrictHostKeyChecking=no root@{{ secrets.SERVER_IP }} './pull_and_run.sh'
